name: mutualfund_gtl
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  http: ^1.2.2 # Updated version for HTTP requests
  jwt_decoder: ^2.0.1
  dio: ^5.1.0
  cookie_jar: ^4.0.0
  dio_cookie_manager: ^3.1.1
  image_picker: ^0.8.6
  path_provider: ^2.0.12

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/

